/* Modelo2_Logico: */

CREATE TABLE CLIENTES (
    RG INTEGER PRIMARY KEY,
    Nome VARCHAR,
    Telefone INTEGER,
    Endereco VARCHAR
);

CREATE TABLE PRODUTOS (
    _Nome_Produto VARCHAR PRIMARY KEY,
    Tipo VARCHAR,
    Preco FLOAT,
    Quantidade_Estoque INTEGER
);

CREATE TABLE REGISTRO_COMPRA (
    DATA DATE,
    VALOR_TOTAL FLOAT,
    FK_CLIENTES_RG INTEGER,
    FK_PRODUTOS__Nome_Produto VARCHAR
);
 
ALTER TABLE REGISTRO_COMPRA ADD CONSTRAINT FK_REGISTRO_COMPRA_1
    FOREIGN KEY (FK_CLIENTES_RG)
    REFERENCES CLIENTES (RG)
    ON DELETE RESTRICT;
 
ALTER TABLE REGISTRO_COMPRA ADD CONSTRAINT FK_REGISTRO_COMPRA_2
    FOREIGN KEY (FK_PRODUTOS__Nome_Produto)
    REFERENCES PRODUTOS (_Nome_Produto)
    ON DELETE RESTRICT;